-- ==============================================================================
-- SCRIPT SQL COMPLETO PARA CONFIGURAÇÃO DAS TABELAS DO AGENTE DE VAGAS NO SUPABASE
-- Execute este script no SQL Editor do seu painel Supabase (https://supabase.com/dashboard)
-- ==============================================================================

-- 1. Habilita extensões necessárias para geração de UUID
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==============================================================================
-- TABELA 1: vagas (Armazena as vagas qualificadas com match >= 80%)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.vagas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    titulo TEXT NOT NULL,
    empresa TEXT,
    link TEXT UNIQUE,
    descricao TEXT,
    match_score INT,
    status TEXT DEFAULT 'QUALIFICADA',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ==============================================================================
-- TABELA 2: vagas_processadas (Histórico e log de todas as vagas analisadas/filtradas)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.vagas_processadas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo_vaga TEXT NOT NULL,
    empresa TEXT,
    link_vaga TEXT,
    match_score INT,
    justificativa TEXT,
    resumo_adaptado TEXT,
    status_candidatura TEXT DEFAULT 'alerta_manual',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Garantir coluna status_candidatura caso a tabela já existisse
ALTER TABLE public.vagas_processadas ADD COLUMN IF NOT EXISTS status_candidatura TEXT DEFAULT 'alerta_manual';

-- ==============================================================================
-- TABELA 3: curriculos_gerados (Armazena os currículos otimizados e payloads JSON)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.curriculos_gerados (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    vaga_id UUID REFERENCES public.vagas(id) ON DELETE CASCADE,
    pdf_url TEXT,
    conteudo_json JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ==============================================================================
-- TABELA 4: prep_dossies (Armazena o dossiê de preparação para entrevistas e perguntas)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.prep_dossies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    vaga_id UUID REFERENCES public.vagas(id) ON DELETE CASCADE,
    resumo_empresa TEXT,
    perguntas_sugeridas JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ==============================================================================
-- ÍNDICES DE DESEMPENHO (Otimização para consultas rápidas)
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_vagas_processadas_created_at ON public.vagas_processadas(created_at);
CREATE INDEX IF NOT EXISTS idx_vagas_created_at ON public.vagas(created_at);
CREATE INDEX IF NOT EXISTS idx_vagas_processadas_link ON public.vagas_processadas(link_vaga);
CREATE INDEX IF NOT EXISTS idx_curriculos_vaga_id ON public.curriculos_gerados(vaga_id);
CREATE INDEX IF NOT EXISTS idx_dossies_vaga_id ON public.prep_dossies(vaga_id);

-- ==============================================================================
-- PERMISSÕES E SEGURANÇA (Row Level Security - RLS)
-- Recomendado: Habilitar RLS e permitir operações seguras via API Key
-- ==============================================================================

-- Libera permissões de execução para os perfis autorizados da aplicação
-- AVISO DE SEGURANÇA: O perfil 'anon' foi removido propositalmente para evitar acesso público irrestrito
GRANT ALL ON public.vagas TO authenticated, service_role;
GRANT ALL ON public.vagas_processadas TO authenticated, service_role;
GRANT ALL ON public.curriculos_gerados TO authenticated, service_role;
GRANT ALL ON public.prep_dossies TO authenticated, service_role;

-- Habilitar RLS (Row Level Security) em todas as tabelas para garantir a conformidade (GRC)
ALTER TABLE public.vagas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vagas_processadas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.curriculos_gerados ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prep_dossies ENABLE ROW LEVEL SECURITY;

